services:

  dff-program-y-ru-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9008
      - PORT=8008

  badlisted-words-ru:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9018
      - PORT=8018

  ner-ru:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9021
      - PORT=8021

  personal-info-ru-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9030
      - PORT=8030

  dff-friendship-ru-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9086
      - PORT=8086

  entity-detection-ru:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9203
      - PORT=8103

  dialogpt-ru:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9091
      - PORT=8091

  toxic-classification-ru:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9126
      - PORT=8126

  spacy-annotator-ru:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9125
      - PORT=8125

  dff-generative-ru-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9092
      - PORT=8092

  dialogrpt-ru:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:9122
      - PORT=8122

version: '3.7'
